#include <iostream>
#include <iomanip> 
using namespace std;
int main() {
	cout<<setw(64)<<setfill('-')<<"-"<<endl  
	<<"|"<<setw(23)<<setfill('\\')<<"\\"<<"|"<<setfill(' ')<<setw(5)<<"|"<<setfill(' ')<<setw(5)<<"|"<<setfill(' ')<<setw(5)<<"|"<<setw(23)<<setfill('\\')<<"\\"<<"|"<<endl
	<<"|"<<setw(3)<<setfill('\\')<<"\\"<<setw(5)<<setfill('-')<<"-"<<setw(7)<<setfill('\\')<<"\\"<<setw(5)<<setfill('-')<<"-"<<setw(3)<<setfill('\\')<<"\\"<<"|"<<setw(4)<<setfill('-')<<"-"<<"|"<<setw(4)<<setfill('-')<<"-"<<"|"<<setw(4)<<setfill('-')<<"-"<<"|"<<setw(3)<<setfill('\\')<<"\\"<<setw(5)<<setfill('-')<<"-"<<setw(7)<<setfill('\\')<<"\\"<<setw(5)<<setfill('-')<<"-"<<setw(3)<<setfill('\\')<<"\\"<<"|"<<endl
	<<"|"<<setw(3)<<setfill('\\')<<"\\"<<setw(5)<<setfill(' ')<<" "<<setw(7)<<setfill('\\')<<"\\"<<setw(5)<<setfill(' ')<<" "<<setw(3)<<setfill('\\')<<"\\"<<"|"<<setw(4)<<setfill(' ')<<" "<<"|"<<setw(4)<<setfill(' ')<<" "<<"|"<<setw(3)<<"X"<<setw(2)<<"|"<<setw(3)<<setfill('\\')<<"\\"<<setw(5)<<setfill(' ')<<" "<<setw(7)<<setfill('\\')<<"\\"<<setw(5)<<setfill(' ')<<" "<<setw(3)<<setfill('\\')<<"\\"<<"|"<<endl
	<<"|"<<setw(3)<<setfill('\\')<<"\\"<<setw(5)<<setfill('-')<<"-"<<setw(7)<<setfill('\\')<<"\\"<<setw(5)<<setfill('-')<<"-"<<setw(3)<<setfill('\\')<<"\\"<<"|"<<setw(4)<<setfill('-')<<"-"<<"|"<<setw(4)<<setfill(' ')<<" "<<"|"<<setw(4)<<setfill('-')<<"-"<<"|"<<setw(3)<<setfill('\\')<<"\\"<<setw(5)<<setfill('-')<<"-"<<setw(7)<<setfill('\\')<<"\\"<<setw(5)<<setfill('-')<<"-"<<setw(3)<<setfill('\\')<<"\\"<<"|"<<endl
	<<"|"<<setw(23)<<setfill('\\')<<"\\"<<"|"<<setfill(' ')<<" "<<setw(2)<<"X"<<setw(2)<<"|"<<setw(4)<<setfill(' ')<<" "<<"|"<<setw(4)<<setfill(' ')<<" "<<"|"<<setw(23)<<setfill('\\')<<"\\"<<"|"<<endl
	<<"|"<<setw(23)<<setfill('\\')<<"\\"<<"|"<<setw(4)<<setfill('-')<<"-"<<"|"<<setw(4)<<setfill(' ')<<" "<<"|"<<setw(4)<<setfill('-')<<"-"<<"|"<<setw(23)<<setfill('\\')<<"\\"<<"|"<<endl
	<<"|"<<setw(23)<<setfill('\\')<<"\\"<<"|"<<setfill(' ')<<setw(5)<<"|"<<setfill(' ')<<setw(5)<<"|"<<setfill(' ')<<setw(5)<<"|"<<setw(23)<<setfill('\\')<<"\\"<<"|"<<endl
	<<"|"<<setw(3)<<setfill('\\')<<"\\"<<setw(5)<<setfill('-')<<"-"<<setw(7)<<setfill('\\')<<"\\"<<setw(5)<<setfill('-')<<"-"<<setw(3)<<setfill('\\')<<"\\"<<"|"<<setw(4)<<setfill('-')<<"-"<<"|"<<setw(4)<<setfill(' ')<<" "<<"|"<<setw(4)<<setfill('-')<<"-"<<"|"<<setw(3)<<setfill('\\')<<"\\"<<setw(5)<<setfill('-')<<"-"<<setw(7)<<setfill('\\')<<"\\"<<setw(5)<<setfill('-')<<"-"<<setw(3)<<setfill('\\')<<"\\"<<"|"<<endl
	<<"|"<<setw(3)<<setfill('\\')<<"\\"<<setw(5)<<setfill(' ')<<" "<<setw(7)<<setfill('\\')<<"\\"<<setw(5)<<setfill(' ')<<" "<<setw(3)<<setfill('\\')<<"\\"<<"|"<<setw(4)<<setfill(' ')<<" "<<"|"<<setw(4)<<setfill(' ')<<" "<<"|"<<setw(4)<<setfill(' ')<<" "<<"|"<<setw(3)<<setfill('\\')<<"\\"<<setw(5)<<setfill(' ')<<" "<<setw(7)<<setfill('\\')<<"\\"<<setw(5)<<setfill(' ')<<" "<<setw(3)<<setfill('\\')<<"\\"<<"|"<<endl 
	<<"|"<<setw(3)<<setfill('\\')<<"\\"<<setw(5)<<setfill('-')<<"-"<<setw(7)<<setfill('\\')<<"\\"<<setw(5)<<setfill('-')<<"-"<<setw(3)<<setfill('\\')<<"\\"<<"|"<<setw(4)<<setfill('-')<<"-"<<"|"<<setw(4)<<setfill(' ')<<" "<<"|"<<setw(4)<<setfill('-')<<"-"<<"|"<<setw(3)<<setfill('\\')<<"\\"<<setw(5)<<setfill('-')<<"-"<<setw(7)<<setfill('\\')<<"\\"<<setw(5)<<setfill('-')<<"-"<<setw(3)<<setfill('\\')<<"\\"<<"|"<<endl 
	<<"|"<<setw(23)<<setfill('\\')<<"\\"<<"|"<<setfill(' ')<<setw(5)<<"|"<<setfill(' ')<<setw(5)<<"|"<<setfill(' ')<<setw(5)<<"|"<<setw(23)<<setfill('\\')<<"\\"<<"|"<<endl
	<<"|"<<setw(62)<<setfill('-')<<"-"<<"|"<<endl
	<<"|"<<setfill(' ')<<setw(4)<<"|"<<setw(2)<<"X"<<setw(2)<<"|"<<setfill(' ')<<setw(4)<<"|"<<setfill(' ')<<setw(4)<<"|"<<setfill(' ')<<setw(4)<<"|"<<setfill(' ')<<setw(4)<<"|"<<setw(15)<<"|"<<setfill(' ')<<setw(4)<<"|"<<setfill(' ')<<setw(4)<<"|"<<setfill(' ')<<setw(4)<<"|"<<setw(2)<<"X"<<setw(2)<<"|"<<setfill(' ')<<setw(4)<<"|"<<setfill(' ')<<setw(4)<<"|"<<endl
	<<"|"<<setw(23)<<setfill('-')<<"-"<<"|"<<setfill(' ')<<setw(15)<<"|"<<setw(23)<<setfill('-')<<"-"<<"|"<<endl
	<<"|"<<setfill(' ')<<setw(4)<<"|"<<setw(20)<<"|"<<setfill(' ')<<setw(15)<<"|"<<setw(20)<<"|"<<setw(4)<<"|"<<endl
	<<"|"<<setw(23)<<setfill('-')<<"-"<<"|"<<setfill(' ')<<setw(15)<<"|"<<setw(23)<<setfill('-')<<"-"<<"|"<<endl
	<<"|"<<setfill(' ')<<setw(4)<<"|"<<setfill(' ')<<setw(4)<<"|"<<setw(2)<<"X"<<setw(2)<<"|"<<setfill(' ')<<setw(4)<<"|"<<setfill(' ')<<setw(4)<<"|"<<setfill(' ')<<setw(4)<<"|"<<setw(15)<<"|"<<setfill(' ')<<setw(4)<<"|"<<setfill(' ')<<setw(4)<<"|"<<setfill(' ')<<setw(4)<<"|"<<setfill(' ')<<setw(4)<<"|"<<setw(2)<<"X"<<setw(2)<<"|"<<setw(4)<<"|"<<endl
	<<"|"<<setw(62)<<setfill('-')<<"-"<<"|"<<endl
	<<"|"<<setw(23)<<setfill('\\')<<"\\"<<"|"<<setfill(' ')<<setw(5)<<"|"<<setfill(' ')<<setw(5)<<"|"<<setfill(' ')<<setw(5)<<"|"<<setw(23)<<setfill('\\')<<"\\"<<"|"<<endl
	<<"|"<<setw(3)<<setfill('\\')<<"\\"<<setw(5)<<setfill('-')<<"-"<<setw(7)<<setfill('\\')<<"\\"<<setw(5)<<setfill('-')<<"-"<<setw(3)<<setfill('\\')<<"\\"<<"|"<<setw(4)<<setfill('-')<<"-"<<"|"<<setw(4)<<setfill(' ')<<" "<<"|"<<setw(4)<<setfill('-')<<"-"<<"|"<<setw(3)<<setfill('\\')<<"\\"<<setw(5)<<setfill('-')<<"-"<<setw(7)<<setfill('\\')<<"\\"<<setw(5)<<setfill('-')<<"-"<<setw(3)<<setfill('\\')<<"\\"<<"|"<<endl
	<<"|"<<setw(3)<<setfill('\\')<<"\\"<<setfill(' ')<<setw(4)<<"R"<<setfill(' ')<<" "<<setw(7)<<setfill('\\')<<"\\"<<setfill(' ')<<setw(4)<<"R"<<setfill(' ')<<" "<<setw(3)<<setfill('\\')<<"\\"<<"|"<<setfill(' ')<<setw(5)<<"|"<<setfill(' ')<<setw(5)<<"|"<<setfill(' ')<<setw(5)<<"|"<<setw(3)<<setfill('\\')<<"\\"<<setw(5)<<setfill(' ')<<" "<<setw(7)<<setfill('\\')<<"\\"<<setw(5)<<setfill(' ')<<" "<<setw(3)<<setfill('\\')<<"\\"<<"|"<<endl
	<<"|"<<setw(3)<<setfill('\\')<<"\\"<<setw(5)<<setfill('-')<<"-"<<setw(7)<<setfill('\\')<<"\\"<<setw(5)<<setfill('-')<<"-"<<setw(3)<<setfill('\\')<<"\\"<<"|"<<setw(4)<<setfill('-')<<"-"<<"|"<<setw(4)<<setfill(' ')<<" "<<"|"<<setw(4)<<setfill('-')<<"-"<<"|"<<setw(3)<<setfill('\\')<<"\\"<<setw(5)<<setfill('-')<<"-"<<setw(7)<<setfill('\\')<<"\\"<<setw(5)<<setfill('-')<<"-"<<setw(3)<<setfill('\\')<<"\\"<<"|"<<endl   
	<<"|"<<setw(23)<<setfill('\\')<<"\\"<<"|"<<setfill(' ')<<setw(5)<<"|"<<setfill(' ')<<setw(5)<<"|"<<setfill(' ')<<setw(5)<<"|"<<setw(23)<<setfill('\\')<<"\\"<<"|"<<endl
	<<"|"<<setw(23)<<setfill('\\')<<"\\"<<"|"<<setw(4)<<setfill('-')<<"-"<<"|"<<setw(4)<<setfill(' ')<<" "<<"|"<<setw(4)<<setfill('-')<<"-"<<"|"<<setw(23)<<setfill('\\')<<"\\"<<"|"<<endl
	<<"|"<<setw(23)<<setfill('\\')<<"\\"<<"|"<<setw(4)<<setfill(' ')<<" "<<"|"<<setw(4)<<setfill(' ')<<" "<<"|"<<setw(3)<<"X"<<setw(2)<<"|"<<setw(23)<<setfill('\\')<<"\\"<<"|"<<endl
	<<"|"<<setw(3)<<setfill('\\')<<"\\"<<setw(5)<<setfill('-')<<"-"<<setw(7)<<setfill('\\')<<"\\"<<setw(5)<<setfill('-')<<"-"<<setw(3)<<setfill('\\')<<"\\"<<"|"<<setw(4)<<setfill('-')<<"-"<<"|"<<setw(4)<<setfill(' ')<<" "<<"|"<<setw(4)<<setfill('-')<<"-"<<"|"<<setw(3)<<setfill('\\')<<"\\"<<setw(5)<<setfill('-')<<"-"<<setw(7)<<setfill('\\')<<"\\"<<setw(5)<<setfill('-')<<"-"<<setw(3)<<setfill('\\')<<"\\"<<"|"<<endl
	<<"|"<<setw(3)<<setfill('\\')<<"\\"<<setfill(' ')<<setw(4)<<"R"<<setfill(' ')<<" "<<setw(7)<<setfill('\\')<<"\\"<<setfill(' ')<<setw(4)<<"R"<<setfill(' ')<<" "<<setw(3)<<setfill('\\')<<"\\"<<"|"<<setfill(' ')<<setw(2)<<"X"<<setw(3)<<"|"<<setw(4)<<setfill(' ')<<" "<<"|"<<setw(4)<<setfill(' ')<<" "<<"|"<<setw(3)<<setfill('\\')<<"\\"<<setw(5)<<setfill(' ')<<" "<<setw(7)<<setfill('\\')<<"\\"<<setw(5)<<setfill(' ')<<" "<<setw(3)<<setfill('\\')<<"\\"<<"|"<<endl  
	<<"|"<<setw(3)<<setfill('\\')<<"\\"<<setw(5)<<setfill('-')<<"-"<<setw(7)<<setfill('\\')<<"\\"<<setw(5)<<setfill('-')<<"-"<<setw(3)<<setfill('\\')<<"\\"<<"|"<<setw(4)<<setfill('-')<<"-"<<"|"<<setw(4)<<setfill('-')<<"-"<<"|"<<setw(4)<<setfill('-')<<"-"<<"|"<<setw(3)<<setfill('\\')<<"\\"<<setw(5)<<setfill('-')<<"-"<<setw(7)<<setfill('\\')<<"\\"<<setw(5)<<setfill('-')<<"-"<<setw(3)<<setfill('\\')<<"\\"<<"|"<<endl  
	<<"|"<<setw(23)<<setfill('\\')<<"\\"<<"|"<<setfill(' ')<<setw(5)<<"|"<<setfill(' ')<<setw(5)<<"|"<<setfill(' ')<<setw(5)<<"|"<<setw(23)<<setfill('\\')<<"\\"<<"|"<<endl
	<<"|"<<setw(62)<<setfill('-')<<"-"<<"|"<<endl;
return 0;
}